import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import AppLayout from "./_components/AppLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " min-h-screen dark"} style={{backgroundColor: "black"}}>
          <Providers>
            
            <AppLayout>
              {children}
            </AppLayout>
            
          </Providers>
        </body>
    </html>
  );
}
